### ISSUE TITLE
Module '"mind-ar-react"' has no exported member 'Scene'.

### ISSUE THREAD

**Issue by Freytag** [krsbx/mind-ar-react#18]
Hello, After seeing that `mind-ar-ts` is used in this library i figured i would give it a try instead but i'm seeing the following problem when using the library. 

Following the readme: 

- Install Mind AR React as Dependencies

```
npm i mind-ar-react
```

- Install Aframe, since it's depends on aframe

```
npm i aframe
```

- Import the components in your React projects

```js
import { Scene, Camera, Box } from 'mind-ar-react';


return (
  /// See the Example one for the structure
);
```

In my file i see a TS error saying: 

> Module '"mind-ar-react"' has no exported member 'Scene'. 

<img width="904" alt="Screen Shot 2022-08-16 at 1 40 53 PM" src="https://user-images.githubusercontent.com/1278024/184981007-f14ae125-3403-4dae-b2b6-8e92024a4005.png">

Also looking at the [`src/Examples/ImageTracking.tsx`](./src/Examples/ImageTracking.tsx), it is importing component from another library of yours. 

`import { Camera, GLTFModel, Plane, Assets, Item } from 'aframe-react-component'`

I know this is still in beta, but these are some issues i'm running into.

**Comment by krsbx** [comment]
thank you for reporting this issues, will look into it

**Comment by Freytag** [comment]
After looking into the `dist` folder this morning I have found that in the `index.js` of the package it is exporting  MindAR.
```javascript
import { Entity, Faces, Marker, Scene } from './components';
const MindAR = {
    Entity,
    Faces,
    Marker,
    Scene,
};
export { MindAR };
export { default as useCompiler } from './utils/useCompiler';
export * from './utils/constant';
export default MindAR;
```

It seems that I can access the Scene this way 
```javascript
import { MindAR } from "mind-ar-react";
...
  return (
    <MindAR.Scene>
```
or this way after disabling our eslint rule
```javascript
// eslint-disable-next-line import/no-named-as-default
import MindAR from "mind-ar-react";
...
  return (
    <MindAR.Scene>
```
hope this helps

**Comment by Freytag** [comment]
But it does appear that this also requires me to install `aframe-react-component` as well since I need to use it for Camera and Assets. 
`// import { Camera, Assets } from 'aframe-react-component';`

**Comment by krsbx** [comment]
I will update the readme this weekend. I believe the `aframe-react-component` was listed as a dep in the package.json, so it should install it right away if its not exist in the projects.

Sorry for this inconvenience since i forgot to update the readme.md.

**Comment by Freytag** [comment]
Thank you for all your work 👍 
`aframe-react-component` is included. I have heard some people say before that if you need to `import` items yourself then it should be included as a dependency in the project. 🤷

**Comment by krsbx** [comment]
will close this issues since in version 0.1.1 its already fixed
